### ISSUE TITLE
can't import pnumpy

### ISSUE THREAD

**Issue by dontmansion1984** [Quansight/pnumpy#155]
Hello. I have an error with importing Pnumpy:
_>>> import pnumpy
Traceback (most recent call last):
  File "<pyshell#198>", line 1, in <module>
    import pnumpy
  File "C:\Python379\lib\site-packages\pnumpy\__init__.py", line 57, in <module>
    import pnumpy._pnumpy as _pnumpy
ImportError: DLL load failed: Can't find the module._
![image (1)](https://user-images.githubusercontent.com/79454953/108706651-7fa86b00-7541-11eb-8548-7a2bbf467111.png)
![image](https://user-images.githubusercontent.com/79454953/108706653-80d99800-7541-11eb-8a40-033d6b6c7f4b.png)

**Comment by mcgfeller** [comment]
Same here - PythonWin 3.8.6, Windows 10.0.19042.867. I tried to copy `_pnumpy.pyd` around to a few locations on the path, nothing helped.

**Comment by danielhrisca** [comment]
The same thing happens on Python 3.9 x64 running on Windows 10
